try {
    throw new error();
    console.log("hello")
    } catch(e) {
    console.log("GoodBye")
    }